cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^shop/cart/$', views.cart_detail, name='cart_detail'),
    url(r'^shop/cart/add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^shop/cart/remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from shop import views as shop_views





urlpatterns = [
    url(r'admin/', include(admin.site.urls)),
    url(r'register/', user_views.register, name='register'),
    url(r'profile/', user_views.profile, name='profile'),
    url(r'login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    url(r'logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    url(r'password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='users/password_reset.html'
         ),
         name='password_reset'),
    url(r'password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='users/password_reset_done.html'
         ),
         name='password_reset_done'),
    url(r'password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='users/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    url(r'password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='users/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    url(r'^', include('store.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('payment.urls', namespace='payment')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),

    # ...
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.product_list, name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.product_detail, name='product_detail'),
]

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products')
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.db.models import Q
from django.contrib.auth.decorators import login_required

@login_required
def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html', {'category': category,
                                                        'categories': categories,
                                                        'products': products})

@login_required
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    {% if title %}
        <title>SJSU Build.R - {{ title }}</title>
    {% else %}
        <title>SJSU Build.R</title>
    {% endif %}
</head>
<style> 

nav {
   background-color: #5f788a; 
}

button[type="submit"]{
    color:#fff;
    background:#5993bb;
    border-radius:4px;
    padding:10px;
    font-size:14px;
    border:0;

}


</style>
<body>
    <div id="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="/home/">SJSU Build.R</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="/home/">Home</a>
                        
                        <a class="nav-item nav-link" href="/about/">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                            <a class="nav-item nav-link" href="/shop/">Shop</a>
                            <a class="nav-item nav-link" href="/profile/">Profile</a>
                            <a class="nav-item nav-link" href="/logout/">Logout</a>
                        {% else %}
                            <a class="nav-item nav-link" href="/login/">Login</a>
                            <a class="nav-item nav-link" href="/register/">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
        <br>
        <br>
    </div>
    <div id="subheader" style="padding-top: 10px;padding-left: 310px;padding-right: 450px;">
        <div id="search" style="display:inline-block;float:left;padding: 10px;">
            <form method="get" action="/search/" class="search-form">   
                <p>
                    <input type="text" name="" placeholder="Search..." style="backgound: white;background-color: white;">
                    <button type="submit">Search</button>
                </p>  
            </form>
        </div>
        <div class="cart"style="display:inline-block;float:right;padding: 10px;">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart: 
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <br style="clear: both;"> 
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>

</body>
</html>